export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const resendKey = process.env.RESEND_API_KEY;
  if (!resendKey) {
    return res.status(500).json({ error: 'RESEND_API_KEY not configured' });
  }

  const { email, flyerUrl, listingName } = req.body;
  if (!email || !flyerUrl) {
    return res.status(400).json({ error: 'email and flyerUrl required' });
  }

  try {
    const r = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${resendKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'Autom8 Real Estate <hello@theoffswitch.co.nz>',
        to: [email],
        subject: `Your listing flyer — ${listingName || 'New Listing'}`,
        html: `
          <div style="font-family:'Helvetica Neue',Arial,sans-serif;max-width:640px;margin:0 auto;background:#f8f7f4;border-radius:12px;overflow:hidden;">
            <div style="background:#1a1916;padding:20px 28px;display:flex;align-items:center;gap:10px;">
              <div style="width:9px;height:9px;border-radius:50%;background:#FF6D3F;"></div>
              <span style="color:#fff;font-size:15px;font-weight:700;">Autom8 <span style="color:#FF6D3F;">Real Estate</span></span>
            </div>
            <div style="padding:28px;">
              <h2 style="font-size:20px;font-weight:700;color:#1a1916;margin:0 0 8px;">Your listing flyer is ready</h2>
              <p style="font-size:13px;color:#5f5e5a;margin:0 0 20px;line-height:1.6;">
                Here's your generated listing flyer for <strong>${listingName || 'your property'}</strong>. 
                Click the image below to view it in full resolution.
              </p>
              <a href="${flyerUrl}" target="_blank" style="display:block;border-radius:10px;overflow:hidden;border:1px solid #e0ddd6;">
                <img src="${flyerUrl}" style="width:100%;display:block;" alt="Listing flyer">
              </a>
              <p style="font-size:11px;color:#9c9a92;margin:16px 0 0;text-align:center;">
                Click the image to open full resolution &nbsp;·&nbsp; Generated by Autom8 Real Estate
              </p>
            </div>
            <div style="background:#1a1916;padding:14px 28px;text-align:center;">
              <span style="font-size:11px;color:rgba(255,255,255,0.4);">Autom8 Real Estate &nbsp;·&nbsp; autom8realestate.co.nz</span>
            </div>
          </div>
        `,
      }),
    });

    const data = await r.json();

    if (!r.ok) {
      return res.status(502).json({ error: 'Resend error', detail: data.message });
    }

    return res.status(200).json({ ok: true, id: data.id });

  } catch (err) {
    return res.status(500).json({ error: 'Send failed', detail: err.message });
  }
}
